spring:
  datasource:
    url: jdbc:postgresql://localhost:{porta_do_container}/microservice_email
    username: {usuario_container}
    password: {password_container}
  mail:
    username: ******************@gmail.com
    password: *******************