spring:
  profiles:
    active: dev
  main:
    banner-mode: off
  output:
    ansi:
      enabled: always
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: true
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
  datasource:
    driver-class-name: org.postgresql.Driver
  flyway:
    locations:
      - db/migrations
  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'