version: "3.1"

services:
  db:
    container_name: ms_email
    image: postgres:14.2-alpine
    restart: always
    env_file:
      - ../config/db.env
    ports:
      - "5431:5432"
  pg:
    container_name: pgadmin
    image: dpage/pgadmin4
    env_file:
      - ../config/pg.env
    ports:
      - "80:80"